name: flutter_keyboard_visibility_web
description: Temporary fork of flutter_keyboard_visibility plugin to address some issues
version: 0.1.1
homepage: https://github.com/EchoEllet/flutter_keyboard_visibility_web
repository: https://github.com/EchoEllet/flutter_keyboard_visibility_web

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  # For web only
  web: ^1.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  mockito: ^5.0.17
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPluginWeb
        fileName: flutter_keyboard_visibility_web.dart